package com.unzer.payment;

/*-
 * #%L
 * Unzer Java SDK
 * %%
 * Copyright (C) 2020 - today Unzer E-Com GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

public enum CommercialSector {

	OTHER,
	WHOLESALE_TRADE_EXCEPT_VEHICLE_TRADE,
	RETAIL_TRADE_EXCEPT_VEHICLE_TRADE,
	WATER_TRANSPORT,
	AIR_TRANSPORT,
	WAREHOUSING_AND_SUPPORT_ACTIVITES_FOR_TRANSPORTATION,
	POSTAL_AND_COURIER_ACTIVITIES,
	ACCOMMODATION,
	FOOD_AND_BEVERAGE_SERVICE_ACTIVITIES,
	MOTION_PICTURE_PRODUCTION_AND_SIMILAR_ACTIVITIES,
	TELECOMMUNICATIONS,
	COMPUTER_PROGRAMMING_CONSULTANCY_AND_RELATED_ACTIVITIES,
	INFORMATION_SERVICE_ACTIVITIES,
	RENTAL_AND_LEASING_ACTIVITIES,
	TRAVEL_AGENCY_AND_RELATED_ACTIVITIES,
	SERVICES_TO_BUILDINGS_AND_LANDSCAPE_ACTIVITIES,
	LIBRARIES_AND_SIMILAR_CULTURAL_ACTIVITIES,
	SPORTS_ACTIVITIES_AND_AMUSEMENT_AND_RECREATION_ACTIVITIES,
	OTHER_PERSONAL_SERVICE_ACTIVITIES,
	NON_RESIDENTIAL_REAL_ESTATE_ACTIVITIES,
	MANAGEMENT_CONSULTANCY_ACTIVITIES,
	ELECTRICITY_GAS_AND_STEAM_SUPPLY,
	WATER_COLLECTION_TREATMENT_AND_SUPPLY,
	SEWERAGE,
	MANUFACTURE_OF_FOOD_PRODUCTS,
	MANUFACTURE_OF_BEVERAGES,
	MANUFACTURE_OF_TEXTILES,
	OTHERS_COMMERCIAL_SECTORS,
	MANUFACTURE_OF_WEARING_APPAREL,
	MANUFACTURE_OF_LEATHER_AND_RELATED_PRODUCTS,
	MANUFACTURE_OF_PHARMACEUTICAL_PRODUCTS,
	REPAIR_AND_INSTALLATION_OF_MACHINERY_AND_EQUIPMENT,
	TRADE_AND_REPAIR_OF_MOTOR_VEHICLES,
	PUBLISHING_ACTIVITIES,
	REPAIR_OF_COMPUTERS_AND_GOODS,
	PRINTING_AND_REPRODUCTION_OF_RECORDED_MEDIA,
	MANUFACTURE_OF_FURNITURE,
	OTHER_MANUFACTURING,
	ADVERTISING_AND_MARKET_RESEARCH,
	OTHER_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_ACTIVITIES,
	ARTS_ENTERTAINMENT_AND_RECREATION

}
