# Trigger security scans in Checkmarx

name: Security Scan

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.github/**', 'docs/**', 'tools/**', 'README.md', 'src/test/**' ]
  workflow_dispatch:
  pull_request:

jobs:
  security-scan:
    uses: unzercorp/unzer-tech-toolbox/.github/workflows/security-scan.yaml@ci-github/1.4
    secrets:
      CX_CLIENT_ID: ${{ secrets.CX_CONNECTIVITY_CLIENT_ID }}
      CX_CLIENT_SECRET: ${{ secrets.CX_CONNECTIVITY_CLIENT_SECRET }}
