name: PR Lint

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  title:
    name: PR title has a ticket reference
    runs-on: ubuntu-latest

    steps:
      - name: Verify PR starts with ticket
        shell: bash
        run: |
          prefix="CC-"
          input="${{ github.event.pull_request.title }}"

          if [[ $input =~ .*${prefix}.* ]]
          then
          	echo "Valid"
          else
          	echo "Not a valid value:"
          	echo "${input}"
            exit 1
          fi
