name: Branch Lint

on:
  pull_request:

jobs:
  title:
    name: Branch has a valid name
    runs-on: ubuntu-latest

    steps:
      - name: Verify branch name
        shell: bash
        run: |
          validate_branch() {
            local branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

            local valid_names=("main")
            for name in "${valid_names[@]}"; do
              if [[ $name == "$branch_name" ]]; then
                return 0
              fi
            done

            local pattern="CC-[0-9]+[/]."
            if [[ $branch_name =~ $pattern ]]; then
              return 0
            fi

            echo "Branch name $branch_name is not allowed."
            echo "Make sure, branch name follows pattern 'CC-{TICKET_NUMBER}/{TICKET_TITLE}'"
            return 1
          }

          validate_branch || exit 1
          echo "Branch name is valid"
